# Generated by Django 5.0.4 on 2025-12-15 20:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('caller_number', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('transcript', models.TextField()),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('sentiment', models.CharField(blank=True, max_length=20)),
                ('transferred', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'call_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(db_index=True, max_length=64, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'email_templates',
                'ordering': ['template_type'],
            },
        ),
        migrations.CreateModel(
            name='EmailEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(max_length=64)),
                ('recipient', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('call', models.ForeignKey(db_column='call_id', on_delete=django.db.models.deletion.CASCADE, related_name='email_events', to='core.calllog', to_field='call_id')),
            ],
            options={
                'db_table': 'email_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_number', models.CharField(blank=True, max_length=64, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('call', models.ForeignKey(db_column='call_id', on_delete=django.db.models.deletion.CASCADE, related_name='transfer_events', to='core.calllog', to_field='call_id')),
            ],
            options={
                'db_table': 'transfer_events',
                'ordering': ['-created_at'],
            },
        ),
    ]
